version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "Europe/Brussels"

  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "Europe/Brussels"

  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "17:00"
      timezone: "Europe/Brussels"
